---
apiVersion: v1
kind: Namespace
metadata:
  name: codens
  labels:
    app: code
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-cm
  namespace: codens
  labels:
    app: code
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: codes-137.184.250.232.nip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: code-secret
  namespace: codens
  labels:
    app: code
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=
